esphome:
  name: altana
  platform: ESP8266
  board: esp07

wifi:
  ssid: !secret wifi_outside_ssid
  password: !secret wifi_outside_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Altana Fallback Hotspot"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: 04
  scl: 05
  scan: False
  id: bus_a
  
mcp23017:
  - id: 'expander'
    address: 0x20

output:
#1st light GPIO 
  - platform: gpio
    pin: 
      mcp23xxx: expander
      # Use pin number 0
      number: 0
    id: Light_1_o
#2nd light GPIO
  - platform: gpio
    pin:
      mcp23xxx: expander
      # Use pin number 1
      number: 1
    id: Light_2_o
#3rd light GPIO
  - platform: gpio
    pin:
      mcp23xxx: expander
      # Use pin number 5
      number: 5
    id: Light_3_o

light:
#1st light switch in Home Assistant 
  - platform: binary
    name: "Światło belka"
    output: Light_1_o
    id: Light_1
#2nd light switch in Home Assistant 
  - platform: binary
    name: "Światło stół 1"
    output: Light_2_o
    id: Light_2
#3rd light switch in Home Assistant 
  - platform: binary
    name: "Światło stół 2"
    output: Light_3_o
    id: Light_3




switch:
#1st pump relay
  - platform: gpio
    name: "Kaskada"
    pin:
      mcp23xxx: expander
      # Use pin number 2
      number: 2
    icon: 'mdi:water-pump'
    id: Pump_1

#2nd pump relay
  - platform: gpio
    name: "Lampa"
    pin:
      mcp23xxx: expander
      # Use pin number 3
      number: 3
    icon: 'mdi:lava-lamp'
    id: Pump_2

#3rd pump relay
  - platform: gpio
    name: "Filtr"
    pin:
      mcp23xxx: expander
      # Use pin number 4
      number: 4
    icon: 'mdi:water'
    id: Pump_3

#Radio relay
  - platform: gpio
    name: "Radio"
    icon: "mdi:radio"
    pin:
      mcp23xxx: expander
      # Use pin number 6
      number: 6

#3rd relay without function yet
  - platform: gpio
    name: "Przekaźniki 3"
    pin:
      mcp23xxx: expander
      # Use pin number 7
      number: 7

binary_sensor:
#1st light button
  - platform: gpio
    pin:
      mcp23xxx: expander
      # Use pin number 8
      number: 8
      mode: INPUT_PULLUP
      inverted: True
    id: L_button_1
    on_press:
      then:
       - light.toggle: Light_1
#2nd and 3rd light button
  - platform: gpio
    pin:
      mcp23xxx: expander
      # Use pin number 9
      number: 9
      mode: INPUT_PULLUP
      inverted: True
    id: L_button_2
    on_press:
        if:
          condition: 
            light.is_on: Light_2
          then:
            - light.turn_off: Light_2
            - light.turn_off: Light_3
          else:
            if:
              condition:
                light.is_on: Light_3
              then: 
                - light.turn_off: Light_2
                - light.turn_off: Light_3
              else: 
                - light.turn_on: Light_2
                - light.turn_on: Light_3

#1st pump button
  - platform: gpio
    pin:
      mcp23xxx: expander
      # Use pin number 10
      number: 10
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on_off: 200ms
    id: P_button_1
    on_press:
      then:
       - switch.toggle: Pump_1

#2nd and 3rd pump button 
  - platform: gpio
    pin:
      mcp23xxx: expander
      # Use pin number 11
      number: 11
      mode: INPUT_PULLUP
      inverted: True
    id: P_button_2
    on_click:
      - min_length: 200ms
        max_length: 5s
        then:
        - switch.toggle: Pump_2
      - min_length: 5s
        max_length: 60s
        then:
          - switch.toggle: Pump_3

