esphome:
  name: parter_jadalnia_taras
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Taras Fallback Hotspot"
    password: !secret captive_portal_password
    
captive_portal:

i2c:

mcp23017:
  - id: 'mcp23017_1'
    address: 0x20

# Enable logging
logger:

# Enable Home Assistant API
api:
  #password: "VQHBFdX!hdT@VKE%xMSA#ciqC6X#!&cK@ZUbj5Nf9&v$PLPa*#PBveyoQmt4DifMcEypk@EU6eDjf%EFnk%tBQzi$&u&3qA^*&*XaKreHQj4k3%9qaGmwhJrPXgefgPG"

ota:

switch:
  - platform: restart
    name: "Taras restart"
#GPIO do sterowania przekaźnikami roletą Taras [T]
  - platform: gpio
    id: gora_t
    pin:
      mcp23xxx: mcp23017_1
      number: 0
    interlock: [gora_t, dol_t]

  - platform: gpio
    pin:
      mcp23xxx: mcp23017_1
      number: 1
    id: dol_t
    interlock: [gora_t, dol_t]

#GPIO do sterowania przekaźnikami roletą Jadalnia 1 [J1]  
  - platform: gpio
    id: gora_j1
    pin:
      mcp23xxx: mcp23017_1
      number: 2
    interlock: [gora_j1, dol_j1]

  - platform: gpio
    pin:
      mcp23xxx: mcp23017_1
      number: 3
    id: dol_j1
    interlock: [gora_j1, dol_j1]

#GPIO do sterowania przekaźnikami roletą Jadalnia 2 [J2]  
  - platform: gpio
    id: gora_j2
    pin:
      mcp23xxx: mcp23017_1
      number: 4
    interlock: [gora_j2, dol_j2]

  - platform: gpio
    pin:
      mcp23xxx: mcp23017_1
      number: 5
    id: dol_j2
    interlock: [gora_j2, dol_j2]

#GPIO do sterowania przekaźnikami roletą Jadalnia 3 [J3]  
  - platform: gpio
    id: gora_j3
    pin:
      mcp23xxx: mcp23017_1
      number: 6
    interlock: [gora_j3, dol_j3]

  - platform: gpio
    pin:
      mcp23xxx: mcp23017_1
      number: 7
    id: dol_j3
    interlock: [gora_j3, dol_j3]


#Buffer taras
  - platform: template
    id: b_buffer_s
    restore_state: off

#Buffer jadalnia
  - platform: template
    id: b_buffer_s_j
    restore_state: off

#Zamykanie rolety taras
binary_sensor:
  - platform: gpio
    pin: 
      number: 13
      mode: INPUT_PULLUP
    id: C_UP
    filters:
      - delayed_on: 10ms
    on_press:
        if:
          condition: 
            switch.is_on: b_buffer_s
          then:
            - cover.stop: roleta_t 
          else: 
            - cover.open: roleta_t
         
#Otwieranie rolety taras
  - platform: gpio
    pin: 
      number: 12
      mode: INPUT_PULLUP
    id: C_DN
    filters:
      - delayed_on: 10ms
    on_press:
        if:
          condition: 
            switch.is_on: b_buffer_s
          then:
            - cover.stop: roleta_t 
          else: 
            - cover.close: roleta_t

#Kontaktron taras
  - platform: gpio
    id: taras
    pin: 
      number: 14
      mode: INPUT_PULLUP
    name: "Taras"
    device_class: window
    on_press: 
      then:
        if:
          condition: 
            not:
              lambda: |-
                return id(roleta_t).position == COVER_OPEN;
          then:
            - cover.open: roleta_t

#Światło 1
  - platform: gpio
    pin:
      mcp23xxx: mcp23017_1
      number: 8
      mode: INPUT_PULLUP
      inverted: false 
    id: L_B1
    filters:
      - delayed_on: 10ms
    on_state:
      - light.toggle: L_1

#Światło 2
  - platform: gpio
    pin:
      mcp23xxx: mcp23017_1
      number: 9
      mode: INPUT_PULLUP
      inverted: false
    id: L_B2
    filters:
      - delayed_on: 10ms
    on_state:
      - light.toggle: L_2

#Rolety jadalnia otwórz
  - platform: gpio
    name: "Rolety parter góra"
    pin:
      mcp23xxx: mcp23017_1
      number: 10
      mode: INPUT_PULLUP
    id: L_B3
    filters:
      - delayed_on: 10ms
    on_state:
        if:
          condition: 
            switch.is_on: b_buffer_s_j
          then:
            - cover.stop: roleta_j1
            - cover.stop: roleta_j2
            - cover.stop: roleta_j3
          else: 
            - cover.open: roleta_j1
            - cover.open: roleta_j2
            - cover.open: roleta_j3

#Rolety jadalnia zamknij
  - platform: gpio
    name: "Rolety parter dół"
    pin:
      mcp23xxx: mcp23017_1
      number: 11
      mode: INPUT_PULLUP
    id: L_B4
    filters:
      - delayed_on: 10ms
    on_state:
        if:
          condition: 
            switch.is_on: b_buffer_s_j
          then:
            - cover.stop: roleta_j1
            - cover.stop: roleta_j2
            - cover.stop: roleta_j3
          else: 
            - cover.close: roleta_j1
            - cover.close: roleta_j2
            - cover.close: roleta_j3

cover:
#Roleta taras
- platform: time_based
  name: "Taras"                             #Nazwa przełącznika
  id: roleta_t                              #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.template.publish:
        id: b_buffer_s
        state: ON
    - switch.turn_on: gora_t                #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 31s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - if:
        condition:
          binary_sensor.is_on: taras
        then:
          if:
            condition: 
              lambda: |-
                return id(roleta_t).position == COVER_OPEN;
            then: 
             - cover.stop: roleta_t
             - delay: 2s
             - cover.open: roleta_t
            else:
             - cover.open: roleta_t
        else:
          - switch.template.publish:
              id: b_buffer_s
              state: ON
          - switch.turn_on: dol_t
  close_duration: 31s
  stop_action:
    - switch.template.publish:
        id: b_buffer_s
        state: OFF
    - switch.turn_off: gora_t
    - switch.turn_off: dol_t

#Roleta jadalnia 1
- platform: time_based
  name: "Jadalnia 1"                        #Nazwa przełącznika
  id: roleta_j1                             #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.template.publish:
        id: b_buffer_s_j
        state: ON
    - switch.turn_on: gora_j1               #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 25s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - switch.template.publish:
        id: b_buffer_s_j
        state: ON
    - switch.turn_on: dol_j1
  close_duration: 25s
  stop_action:
    - switch.template.publish:
        id: b_buffer_s_j
        state: OFF
    - switch.turn_off: gora_j1
    - switch.turn_off: dol_j1

#Roleta jadalnia 2
- platform: time_based
  name: "Jadalnia 2"                        #Nazwa przełącznika
  id: roleta_j2                             #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.template.publish:
        id: b_buffer_s_j
        state: ON
    - switch.turn_on: gora_j2               #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 25s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - switch.template.publish:
        id: b_buffer_s_j
        state: ON
    - switch.turn_on: dol_j2
  close_duration: 25s
  stop_action:
    - switch.template.publish:
        id: b_buffer_s_j
        state: OFF
    - switch.turn_off: gora_j2
    - switch.turn_off: dol_j2

#Roleta jadalnia 3
- platform: time_based
  name: "Jadalnia 3"                        #Nazwa przełącznika
  id: roleta_j3                             #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.template.publish:
        id: b_buffer_s_j
        state: ON
    - switch.turn_on: gora_j3               #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 25s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - switch.template.publish:
        id: b_buffer_s_j
        state: ON
    - switch.turn_on: dol_j3
  close_duration: 25s
  stop_action:
    - switch.template.publish:
        id: b_buffer_s_j
        state: OFF
    - switch.turn_off: gora_j3
    - switch.turn_off: dol_j3

output:
#Wyjście światło 1
  - platform: gpio
    id: L_O1
    pin:
      mcp23xxx: mcp23017_1
      number: 12
#Wyjście światło 2
  - platform: gpio
    id: L_O2
    pin:
      mcp23xxx: mcp23017_1
      number: 13

light:
#Przełącznik światła 1
  - platform: binary
    name: "Lampy zewnątrz"
    id: L_1
    output: L_O1

#Przełącznik światła 2
  - platform: binary
    name: "Taras"
    id: L_2
    output: L_O2
