esphome:
  name: pokoj_gospodarczy
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pokoj Gospodarczy"
    password: !secret captive_portal_password

captive_portal:

#zdefiniowanie wyjść (GPIO) dla LEDów (PWM)
output:
  - platform: esp8266_pwm
    id: led
    pin: 4

#Przekaźnik sterujący zaworem
switch:
  - platform: gpio
    pin:
      number: 2
      inverted: false
    name: "Zawór"
    id: zawor
  - platform: template
    name: Alarm
    id: alarm
    turn_off_action: 
     if:
      condition:
        binary_sensor.is_on: led_s
      then:
        - delay: 100ms
        - light.turn_on: 
            id: led_l
            brightness: 100%
      else:
        - light.turn_off: led_l

binary_sensor:
#Kontrakton przełączający LEDy
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    id: led_s
    on_press:
      then:
      - output.turn_on: led
    on_release:
      then:
      - output.turn_off: led
#Czujnik zalania
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    id: zawor_b
    on_press:
      then:
        - switch.turn_on: zawor
        - switch.turn_on: alarm
        - while:
            condition:
              switch.is_on: alarm
            then:
              - light.turn_on: 
                  id: led_l
                  brightness: 100%
              - delay: 500ms
              - light.turn_off: led_l
              - delay: 500ms

#Sterownik LEDów
light:
  - platform: monochromatic
    name: "Światło pokój gospodarczy"
    id: led_l
    output: led

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
