esphome:
  name: pokoj_gospodarczy
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pokoj Gospodarczy"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#zdefiniowanie wyjść (GPIO) dla LEDów (PWM)
output:
  - platform: esp8266_pwm
    id: led
    pin: 4

#skrypt alarmu
script: 
  - id: alarm_scr
    then: 
      - switch.turn_on: zawor
      - delay: 300ms
      - while:
          condition:
            switch.is_on: alarm
          then:
            - light.turn_on: 
                id: led_l
                brightness: 100%
            - delay: 1000ms
            - light.turn_off: led_l
            - delay: 1000ms

#Przekaźnik sterujący zaworem
switch:
  - platform: gpio
    pin:
      number: 2
      inverted: false
    name: "Zawór"
    icon: mdi:valve
    id: zawor
    
#Przycisk od alarmu
  - platform: template
    name: Alarm
    id: alarm
    icon: mdi:alarm-light
    turn_on_action: 
      if:
        condition: 
          binary_sensor.is_on: zawor_b
        then: 
          - script.execute: alarm_scr
          - lambda: |-
              id(alarm).publish_state(true);
    turn_off_action: 
      - if:
          condition: 
            script.is_running: alarm_scr
          then:
            - script.stop: alarm_scr
            - delay: 500ms
            - if:
                condition:
                  binary_sensor.is_on: led_s
                then:
                  - delay: 100ms
                  - light.turn_on: 
                      id: led_l
                      brightness: 100%
                else:
                  - light.turn_off: led_l
      - lambda: |-
          id(alarm).publish_state(false);

binary_sensor:
#Kontrakton przełączający LEDy
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    id: led_s
    on_press:
      then:
        light.turn_on: 
          id: led_l
          brightness: 100%
    on_release:
      then:
      - light.turn_off: led_l
#Czujnik zalania
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    id: zawor_b
    on_press:
      then:
        - delay: 500ms
        - switch.turn_on: alarm


#Przycisk od LEDów
  - platform: gpio
    pin: 
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    id: led_sw
    on_press: 
      light.toggle: led_l

#Przycisk od alarmu
  - platform: gpio
    pin: 
      number: 5
      mode: INPUT_PULLUP
      inverted: true
    id: alarm_sw
    on_press: 
      switch.turn_off: alarm

#Przycisk od zaworu
  - platform: gpio
    pin: 
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    id: zawor_sw
    on_press: 
      switch.toggle: zawor
      


#Sterownik LEDów
light:
  - platform: monochromatic
    name: "Światło pokój gospodarczy"
    id: led_l
    output: led
