esphome:
  name: roleta_taras
  platform: ESP8266
  board: esp12e
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roleta Taras"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#GPIO do sterowania przekaźnikami
switch:
- platform: gpio
  pin:
    number: 0
    inverted: yes
  interlock: &interlock [open_cover, close_cover]
  id: open_cover

- platform: gpio
  pin:
    number: 4
    inverted: yes
  interlock: *interlock 
  id: close_cover

- platform: restart
  name: "Roleta taras restart"

cover:
- platform: time_based
  name: "Taras"                             #Nazwa przełącznika
  id: roleta_taras                          #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.turn_on: open_cover            #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 31s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - switch.turn_on: close_cover
  close_duration: 31s
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover