esphome:
  name: sypialnia_jakub_monika_tomek
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sypialnia Fallback Hotspot"
    password: !secret captive_portal_password
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  #password: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI4NTFhMzBhY2Q1MWI0ODUwYmYxMzNkOTBjNDI3NzRjYSIsImlhdCI6MTU4NjQ2MTExNywiZXhwIjoxOTAxODIxMTE3fQ.vzXJHiYQuOn38OswB6y91xeM-_JUazjrOkCQR7tTZSk"

web_server:
  port: 80

ota:

switch:

#GPIO do sterowania przekaźnikami w sypialni Moniki i Tomka [MT]
- platform: gpio
  id: gora_MT
  pin: 5
  interlock: [gora_MT, dol_MT]

- platform: gpio
  id: dol_MT
  pin: 2
  interlock: [gora_MT, dol_MT]

#GPIO do sterowania przekaźnikami w sypialni Jakub [J]
- platform: gpio
  id: gora_J
  pin: 0
  interlock: [gora_J, dol_J]

- platform: gpio
  pin: 4
  id: dol_J
  interlock: [gora_J, dol_J]

- platform: restart
  name: "Jakub, Monika, Tomek restart"

cover:
- platform: time_based
  name: "Monika i Tomek"                    #Nazwa przełącznika
  id: roleta_MT                             #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.turn_on: gora_MT               #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 31s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - switch.turn_on: dol_MT
  close_duration: 31s
  stop_action:
    - switch.turn_off: gora_MT
    - switch.turn_off: dol_MT

- platform: time_based
  name: "Jakub"                             #Nazwa przełącznika
  id: roleta_J                              #ID przełącznika
  open_action:                              #Co się dzieję kiedy kliknę przycisk OPEN
    - switch.turn_on: gora_J                #Włącz przełącznik (SWITCH) odpowiedzialny za jazdę w górę
  open_duration: 31s                        #Czas zamykania rolety (31 sekund) 
  close_action:
    - switch.turn_on: dol_J
  close_duration: 31s
  stop_action:
    - switch.turn_off: gora_J
    - switch.turn_off: dol_J
