esphome:
  name: test
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: !secret captive_portal_password
    
captive_portal:

# Enable logging
logger:

ota:

# Enable Home Assistant API
api:

dallas:
  - pin: GPIO12
    update_interval: 180s

i2c:
  sda: 04
  scl: 05
  scan: False
  id: bus_a
  
mcp23017:
  - id: 'expander'
    address: 0x20

output:
  #1st light GPIO 
    - platform: gpio
      pin: 
        mcp23xxx: expander
        # Use pin number 0
        number: 0
      id: Light_1_o
  #2nd light GPIO
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 1
        number: 1
      id: Light_2_o
  #3rd light GPIO
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 5
        number: 5
      id: Light_3_o
  
  #Solar thermal collector output
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 7
        number: 7
      id: collector_o

light:
  #1st light switch in Home Assistant 
    - platform: binary
      name: "Światło belka"
      output: Light_1_o
      id: Light_1
  #2nd light switch in Home Assistant 
    - platform: binary
      name: "Światło stół 1"
      output: Light_2_o
      id: Light_2
  #3rd light switch in Home Assistant 
    - platform: binary
      name: "Światło stół 2"
      output: Light_3_o
      id: Light_3

switch:
  #1st pump relay
    - platform: gpio
      name: "Kaskada"
      pin:
        mcp23xxx: expander
        # Use pin number 2
        number: 2
      icon: 'mdi:water-pump'
      id: Pump_1
  
  #2nd pump relay
    - platform: gpio
      name: "Lampa"
      pin:
        mcp23xxx: expander
        # Use pin number 3
        number: 3
      icon: 'mdi:lava-lamp'
      id: Pump_2
  
  #3rd pump relay
    - platform: gpio
      name: "Filtr"
      pin:
        mcp23xxx: expander
        # Use pin number 4
        number: 4
      icon: 'mdi:water'
      id: Pump_3
  
  #Radio relay
    - platform: gpio
      name: "Radio"
      icon: "mdi:radio"
      pin:
        mcp23xxx: expander
        # Use pin number 6
        number: 6
  
  #1st solar thermal collector switch
    - platform: template
      name: "Kolektory - auto"
      id: collector_s_1
      icon: mdi:brightness-auto
      turn_off_action: 
        - output.turn_off: collector_o
        - binary_sensor.template.publish:
            id: pump_state
            state: OFF
  
  #2nd solar thermal collector switch
    - platform: template
      name: "Kolektory - manual"
      id: collector_s_2
      icon: mdi:water-boiler
      turn_on_action: 
        - output.turn_on: collector_o
        - binary_sensor.template.publish:
            id: pump_state
            state: ON
      turn_off_action: 
        - output.turn_off: collector_o
        - binary_sensor.template.publish:
            id: pump_state
            state: OFF

binary_sensor:
  #1st light button
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 8
        number: 8
        mode: INPUT_PULLUP
        inverted: True
      id: L_button_1
      on_press:
        then:
         - light.toggle: Light_1
  #2nd and 3rd light button
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 9
        number: 9
        mode: INPUT_PULLUP
        inverted: True
      id: L_button_2
      on_press:
          if:
            condition: 
              light.is_on: Light_2
            then:
              - light.turn_off: Light_2
              - light.turn_off: Light_3
            else:
              if:
                condition:
                  light.is_on: Light_3
                then: 
                  - light.turn_off: Light_2
                  - light.turn_off: Light_3
                else: 
                  - light.turn_on: Light_2
                  - light.turn_on: Light_3
  
  #1st pump button
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 10
        number: 10
        mode: INPUT_PULLUP
        inverted: True
      filters:
        - delayed_on_off: 200ms
      id: P_button_1
      on_press:
        then:
         - switch.toggle: Pump_1
  
  #2nd and 3rd pump button 
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 11
        number: 11
        mode: INPUT_PULLUP
        inverted: True
      id: P_button_2
      on_click:
        - min_length: 200ms
          max_length: 5s
          then:
          - switch.toggle: Pump_2
        - min_length: 5s
          max_length: 60s
          then:
            - switch.toggle: Pump_3
  
  #1st solar thermal collector auto pump
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 12
        number: 12
        mode: INPUT_PULLUP
        inverted: True
      id: C_button_1
      on_press:
        then:
         - switch.toggle: collector_s_1
  
  #2nd solar thermal collector manual pump
    - platform: gpio
      pin:
        mcp23xxx: expander
        # Use pin number 13
        number: 13
        mode: INPUT_PULLUP
        inverted: True
      id: C_button_2
      on_press:
        then:
         - switch.toggle: collector_s_2

  #Pump state
    - platform: template 
      id: pump_state
      name: "Pompa"
      device_class: power

sensor:
  #Water input temperature in solar thermal collector 
    - platform: dallas
      address: 0x1c0000031edd2a28
      name: "Temperatura w kolektorach"
      
      on_value_range:
        #Above 34 degrees Celsius turn on pump
        - above: 34
          then: 
            if:
              condition:
                switch.is_on: collector_s_1
              then: 
                if: 
                  condition: 
                    switch.is_off: collector_s_2
                  then:
                    - output.turn_on: collector_o
                    - binary_sensor.template.publish:
                        id: pump_state
                        state: ON
        #Below 34 degrees Celsius turn off pump
        - below: 34
          then: 
            if:
              condition:
                switch.is_on: collector_s_1
              then: 
                if: 
                  condition: 
                    switch.is_off: collector_s_2
                  then:
                    - output.turn_off: collector_o
                    - binary_sensor.template.publish:
                        id: pump_state
                        state: OFF
  #Water output temperature in solar thermal collector 
    - platform: dallas 
      address: 0x1c0000031edd2a28
      name: "Temperatura na wyjściu"
  #Outside temperature
    - platform: dallas 
      address: 0x1c0000031edd2a28
      name: "Temperatura w cieniu"
